
package WS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebServiceClient;


/**
 * This Webservice provides an easy way to retrieve our product information.
 * 
 * POUR MOUSER
 
 This class was generated by the JAX-WebService RI.
 JAX-WebService RI 2.1.6 in JDK 6
 Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SearchAPI", targetNamespace = "http://api.mouser.com/service", wsdlLocation = "http://www.mouser.fr/service/searchapi.asmx?WSDL")
public class SearchAPI
    extends Service
{
    
    private final static URL SEARCHAPI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WS.SearchAPI.class.getName());
    
    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WS.SearchAPI.class.getResource(".");
            url = new URL(baseUrl, "http://api.mouser.fr/service/searchapi.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://api.mouser.fr/service/searchapi.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SEARCHAPI_WSDL_LOCATION = url;
    }

    public SearchAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchAPI() {
        super(SEARCHAPI_WSDL_LOCATION, new QName("http://api.mouser.com/service", "SearchAPI"));
    }

}
